# Generated by Django 2.1 on 2018-09-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rent', models.CharField(max_length=10000)),
                ('locality', models.CharField(max_length=10000)),
                ('property_type', models.CharField(max_length=10000)),
            ],
        ),
    ]
