# Generated by Django 2.1 on 2018-09-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20180909_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
