# Generated by Django 2.1 on 2018-09-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20180910_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='building',
            new_name='address',
        ),
    ]
