# Generated by Django 2.1 on 2018-09-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20180910_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='BHK',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('>5', '>5')], max_length=10000),
        ),
    ]
