# Generated by Django 2.1 on 2018-09-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20180910_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_title',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
