# Generated by Django 2.1 on 2018-09-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20180911_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='buy_rent',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=10000),
        ),
    ]
