# Generated by Django 2.1 on 2018-09-10 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='property_title',
            new_name='property',
        ),
    ]
